### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by BloodyIron** [kubernetes-sigs/nfs-subdir-external-provisioner#210]
Can we please get actual notes of what changed with each release in the GitHub Release Notes section? :)

Can't tell why I should upgrade with out it, really.

**Comment by yonatankahana** [comment]
we do have [`CHANGELOG.md`](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/CHANGELOG.md) to track changes in the provisioner itself.
most of the releases are helm chart releases (sometimes its just changes in the README), are you talking about change log for helm charts?

**Comment by BloodyIron** [comment]
I'm talking about this page : https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases

**Comment by lnhrdt** [comment]
I'd also appreciate an explanation of changes for each release to help decide how much independent testing is warranted before I use a new release in production clusters. Even if it is just documentation updates etc it would be helpful to call that out.

Personally I looked for it in the GitHub Releases first, CHANGELOG.md second, and when I saw there were no notes for any recent releases I came here.

**Comment by BloodyIron** [comment]
Yeah I plan to keep up with this project as it's going to be core to infra I run. I really would like to know what each release has, and github release notes are a really great way to do that. I also don't use helm charts for my implementation.

**Comment by BloodyIron** [comment]
Hey so @yonatankahana changelog.md stopped getting updated... 17 months ago...

How about we get release notes in each release on the github page instead? That would help a lot more.

**Comment by lnhrdt** [comment]
@tinguin I see you made [the commit that triggered the latest release (4.0.17)](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/commit/6d07787c03e253693802b40b21c2187549cf6680). What's the best way to understand the changes?

**Comment by lnhrdt** [comment]
/reopen

/remove-lifecycle rotten

@justdan96 I know it was over a year ago, but I see you made [the commit that triggered the latest release (4.0.18)](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/commit/8af604bdc7e8076b8482b1652b7c139abb1659a9). When I'm upgrading nfs-subdir-external-provisioner in clusters it would help to understand the changes made. What's the best way to understand the changes?

**Comment by justdan96** [comment]
@lnhrdt all the info you want is in the PR https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/267

**Comment by lnhrdt** [comment]
Fantastic and thank you @justdan96! This is really helpful to understand but hard to navigate as a non-contributor.

One thing I noticed that might help users like me is to more clearly distinguish the publication of your helm chart and the provisioner itself. It seems this issue, #96, and #304 are all symptoms of this ambiguity. I know I have even forgotten this tricky detail about your project multiple times over the last couple years, each time I come back to check for updates.

I see @yonatankahana [explained it to another confused user here](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/96#issuecomment-830653796) and I've benefited from re-reading that comment over the years but it seems to me this information could be made more clear for the project and its users.

I think the issue is that no distinction is made between helm charts and the provisioner on [your releases page](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases). To a user (non-contributor) who's not intimately familiar with the project, it would appear there is a v4.0.18 of this library.
<img width="824" alt="Screenshot 2024-04-18 at 09 42 08" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/4040241/e691c6ad-ec04-4c49-8246-9d5a4426b427">

However as you know, there is only a v4.0.2 of this library, with a pending v4.0.3 on its way, and a v4.0.18 of the helm chart. It's just a little hard to learn that in this project, as a newcomer.

I like the way ingress-nginx handles this. They clearly label the helm chart releases vs controller releases [on their releases page](https://github.com/kubernetes/ingress-nginx/releases):
<img width="1068" alt="Screenshot 2024-04-18 at 09 46 12" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/4040241/5cfbf4e9-5124-4901-a12f-02883f4b54a8">

And [in their README](https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#changelog) they show how to understand the changes for the controller and for the helm chart:
<img width="862" alt="Screenshot 2024-04-18 at 09 47 01" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/4040241/c149b93f-e1a7-4df7-9d9a-53f4d1ca5609">

Is it possible this project would consider clarifying your releases in a similar way?

**Comment by justdan96** [comment]
@lnhrdt Sorry I'm not a representative of this project, I just sent the PR for that change. Maybe you could update the changelog with all the missing entries and send your own PR?
