### ISSUE TITLE
--set nfs.mountOptions="nobrl" fails on helm install

### ISSUE THREAD

**Issue by Lizalex-Systems** [kubernetes-sigs/nfs-subdir-external-provisioner#229]
Hi - if --set nfs.mountOptions="nobrl" is passed to helm the install fails with an "unable to iterate over range nobrl" - is it just that I have the syntax incorrect or that the nfs.mountOptions does not support single word switches ( i.e. 'nobrl' ) and only named value pair settings ( e.g. 'nfsvers=3' ) ?

**Comment by 6rendel** [comment]
Same for hard or noresvport options

`Error: INSTALLATION FAILED: failed parsing --set data: key "hard" has no value (cannot end with ,)`

**Comment by 6rendel** [comment]
@Lizalex-Systems 

you can download the values file:
https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/master/charts/nfs-subdir-external-provisioner/values.yaml
fill all the details and instead of using all these --set just use -f values.yaml
It then installs just fine

hope that helps

**Comment by cccsss01** [comment]
I wrote mountOptions: [nfsvers=4.1] in the values file.
