### ISSUE TITLE
nfs-client-provisioner pod not creating  when nfs share is without insecure option

### ISSUE THREAD

**Issue by ZrytyADHD** [kubernetes-sigs/nfs-subdir-external-provisioner#283]
Hi,
I use kubernetes nfs-subdir-external-provisioner on Tanzu and have problem. 
I deploy it on test cluster configure nfs server and share properly start deploy and got error.
When i set nfs exports like this:
/tanzu <my ip adress from where connecting>(rw,sync,no_subtree_check,no_root_squash)

pod show me error:
/var/lib/kubelet/pods/8b203f8b-0074-4e68-bcb9-b125cff0a281/volumes/kubernetes.io~nfs/nfs-client-root
Output: mount.nfs: access denied by server while mounting <nfs server>:/tanzunfs

but when I use in exports this one:
/tanzu <my ip adress from where connecting>(rw,sync,no_subtree_check,no_root_squash,insecure)

the problem is not existing.

I need to have secure connection betwen my cluster and nfs server.
Can anyone know how to resolve this ?

One more question there is an option to set specific port for nfs-provisoner not random one when pod is creating

**Comment by maykopetersen** [comment]
Run `rpcinfo -p | grep nfs` command in your NFS Server:
```
root@nfsserver:~# rpcinfo -p | grep nfs
    100003    3   tcp   2049  nfs
    100003    4   tcp   2049  nfs
    100003    3   udp   2049  nfs
```
You'll see something as above. 

Read:
> The TCP ports 1-1024 are reserved for root's use (and therefore sometimes referred to as "secure ports") A non-root user cannot bind these ports. Adding the "secure" option to an "/etc/exports" means that it will only listed to requests coming from ports 1-1024 on the client, so that a malicious non-root user on the client cannot come along and open up a spoofed NFS dialogue on a non-reserved port. This option is set by default

Source: https://tldp.org/HOWTO/NFS-HOWTO/security.html

In other words: NFS uses 2049 port to allow connections and if you DON'T use `insecure` option in `/etc/exports` , your service will block the requestions that call this port because it will only accept 1-1024 port range.

If you _need to have secure connection between your cluster and your nfs server_, start delete `no_root_squash` option and add only your  cluster IP  in the `/etc/export`. Example:
`/home/DATA     clusterName(rw,no_all_squash,root_squash,anonuid=<UIDNumber>,anongid=<GIDNumber>,sync,no_subtree_check,crossmnt,insecure)
`
P.S.: `UIDNumber` and `GIDNumber` refer `user` and `group` with access your `/tanzu` directory. NEVER use `rwxrwxrwx` in your directory and NEVER use `nobody` group.
