### ISSUE TITLE
Is the v4.0.3 version about to be released soon

### ISSUE THREAD

**Issue by hollycai05** [kubernetes-sigs/nfs-subdir-external-provisioner#330]
I noticed the v4.0.3 changeLog in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/CHANGELOG.md. 
Does this mean that v4.0.3 will be released soon? There are some high CVEs in v4.0.2 (or the newer version 4.0.18 release), so really looking forward to v4.0.3 being released ASAP. 
Thanks

**Comment by flo-mic** [comment]
@hollycai05 while 4.0.3 is not released, you can still rebuild the provisioner on your own to get rid of the high vulnerabilities. Here some example dockerfile to build the latest provisioner

```
FROM golang:1.19 as builder
RUN git clone https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner 
WORKDIR /go/nfs-subdir-external-provisioner
RUN make

FROM gcr.io/distroless/static:latest
ARG binary=./bin/nfs-subdir-external-provisioner
COPY --from=builder /go/nfs-subdir-external-provisioner/bin/nfs-subdir-external-provisioner /nfs-subdir-external-provisioner
ENTRYPOINT ["/nfs-subdir-external-provisioner"]
```

**Comment by yonatankahana** [comment]
> @hollycai05 while 4.0.3 is not released, you can still rebuild the provisioner on your own to get rid of the high vulnerabilities. Here some example dockerfile to build the latest provisioner
> 
> ```
> FROM golang:1.19 as builder
> RUN git clone https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner 
> WORKDIR /go/nfs-subdir-external-provisioner
> RUN make
> 
> FROM gcr.io/distroless/static:latest
> ARG binary=./bin/nfs-subdir-external-provisioner
> COPY --from=builder /go/nfs-subdir-external-provisioner/bin/nfs-subdir-external-provisioner /nfs-subdir-external-provisioner
> ENTRYPOINT ["/nfs-subdir-external-provisioner"]
> ```

you can also use pre-built RC image: `quay.io/yonatankahana/nfs-subdir-external-provisioner:v4.0.3-rc2`

**Comment by rishithaminol** [comment]
@yonatankahana What about golang 1.22.1.

Have you tried that?

**Comment by yonatankahana** [comment]
> @yonatankahana What about golang 1.22.1.
> 
> Have you tried that?

not yet, I will try to find some time in the weekend.

**Comment by Starttoaster** [comment]
I'm currently in the process of forking this repo and making my own release to clear up my trivy dashboard, as this is currently the most vulnerable thing running in my cluster, with 3 critical CVEs, and based on an end-of-service-life base OS image. Would be cool to get an update on if this could get some first party support time though. Understand of course that many FOSS projects are often maintained by one unpaid individual :) This one was just surprising to me being underneath kubernetes-sigs. Is there a more maintained NFS subdir provisioner project out there?

**Comment by Starttoaster** [comment]
Happy to say I have my fork of this project up and operational in my cluster. It was somewhat not an easy task, at least for me, since I hadn't used the upstream https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner library this project uses before. This was previously the most vulnerable thing running in my cluster with 3 critical CVEs, 56 high CVEs, and an end-of-service-life base image, to no recorded CVEs in my fork (according to Trivy.)

*Updates:*
* I updated Golang to latest - this appeared to be a free update without consequences.
* I switched to a distroless base image - this appeared to be a free change without consequences.
* I updated all the kubernetes client-go (and related k8s toolkit modules) - this was an update that had consequences, requiring a huge update to the sig-storage-lib-external-provisioner dependency from v6 (used by this repo) to v10 (the latest release of the upstream library.) It also required some code changes that seem fairly trivial imho to satisfy the new interface of the sig-storage-lib-external-provisioner library. It also required some RBAC changes in the helm chart. If the maintainers here have been hesitant to show this project any love recently, I assume this update is what they've been dreading figuring out.

The majority of this work happened in the following pull requests:
* https://github.com/Starttoaster/nfs-subdir-external-provisioner/pull/1
* https://github.com/Starttoaster/nfs-subdir-external-provisioner/pull/4
* https://github.com/Starttoaster/nfs-subdir-external-provisioner/pull/5 - (helm chart change only)

The first link will be hard to read, because I also deleted whole directories of fluff (or what I consider fluff) like the vendors directory (we use go modules here, I don't want to pollute the source code with all that vendor code.) And the huge release helper directory, which didn't really serve a purpose in my fork, my release workflows I add to most of my projects seem to replace their function sufficiently. 
For reasons I also could not divine if you asked, this repo also contained like 6 different Dockerfiles, which I reduced to 1, because who knows what build artifact you're actually getting with all these Dockerfiles? Seriously, why so many Dockerfiles?
I also deleted the kustomize deploy option -- this is a change I'm somewhat okay with reversing. But I figured it would be easier for me to solely maintain this product with only one deployment option. And I don't use kustomize as often, so I chose to keep helm.

I can't say that I really recommend everyone switch to my fork. I won't do an amazing job of maintaining it, to be frank. But I can say that I have personally been very tired of seeing this stare at me from the top of my cluster vulnerabilities dashboard. This will be so much easier to maintain anyway just using a distroless base image. So if you choose to migrate to my fork, beware that my version is intended to be little more than a stopgap for the upstream (this project) to see maintainership time again. And if the maintainers here want to peek at my fork for help with updating this repo to the new, PLEASE, do not hesitate. ... What I _will_ do, however, is try to keep on top of updates and CVEs, and read as well as respond to Issues.

*To update:*
If you're a user of the helm chart here, there isn't anything you need to do other than switch from their helm repo, to my helm repo, and run `helm upgrade`. Disclaimer: I frankly don't know that I can recommend running this fork in production in a company setting, and I'll take NO responsibility for any service downtime rendered from a bad change in my fork. What I can say though is, "works for me, and is massively more up to date than this project is (at time of writing.)

**Comment by Starttoaster** [comment]
Also to the maintainers, if you want to see these updates in this repo I can take a stab at contributing them. In my opinion your repository is quite a bit more complicated to actually contribute to than mine. But I might have the time one of these days to take some stabs at PRs here, but basically my investment here was needing to update _everything_ because pretty much _everything_ is incredibly out of date. So in return I'd ask the maintainers here to review my fork, and tell me what you want me to carry over to this repo specifically. Which I think would be more productive because the time you give to this project seem fairly limited, so I would like to not spend months going back and forth waiting for PR comment correspondence for feedback.
