### ISSUE TITLE
Change nfs path without reinstalling helm package

### ISSUE THREAD

**Issue by AlistairMcCutcheonIAS** [kubernetes-sigs/nfs-subdir-external-provisioner#331]
I've been using this for some time, but I need to change the nfs path that I'm using. I have several persistent volumes which I don't want to delete. 
As per the readme, the way to install the helm package is:
```
helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=x.x.x.x \
    --set nfs.path=/exported/path
```

But is there any way to change the nfs.path after it is installed please?

**Comment by Orhideous** [comment]
It is not possible to change the path in existing volumes.

Rename/move the data folder on the NFS server (if the `archiveOnDelete` policy is not set), then delete pv/pvc, then move the data back to its place.

In the case of a database, temporary replace the command with `["/bin/sleep", "infinity"]` to maintain data consistency.

**Comment by Orhideous** [comment]
Well, since https://github.com/kubernetes/kubernetes/issues/54562 configuration for NFS volumes is effectively _set in stone_, so there are no easy way to move data automatically.

Nevertheless, I removed the stale label, because this issue can be addressed, at least with mention of some workarounds in the docs.
